### ISSUE TITLE
Github workflows

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/Phylo.jl#35]
Do you want me to update the `.github` folder to use actions to build everything?

**Comment by claireh93** [comment]
I have mostly got actions to work in #44 but there seems to be a problem with some python in the docs build that is still outstanding https://github.com/EcoJulia/Phylo.jl/runs/1790952405?check_suite_focus=true
I don't have time to address it at the moment, but if anyone has any ideas then let me know!
