### ISSUE TITLE
DataFrames upper version

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/Phylo.jl#36]
Is there a reason for the `^0.20` upper limit on the `DataFrames` version? I am trying to plug the results of `NCBITaxonomy` into a tree, but the set of versions don't overlap. I'm willing to attempt a fix that would let us use the most recent `DataFrames` release.

**Comment by mkborregaard** [comment]
Yes let's definitely update. There was a big syntax change between DataFrames 0.20 and 0.21 but we should use the recent one.
To me it only looks like we even need a version number on it in the `test` folder.
